package main

import (
	"context"
	"errors"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestPlatformAssetName(t *testing.T) {
	tests := []struct {
		goos    string
		goarch  string
		want    string
		wantErr bool
	}{
		{"linux", "amd64", "libdcap_qvl_linux_amd64.a", false},
		{"linux", "arm64", "libdcap_qvl_linux_arm64.a", false},
		{"darwin", "amd64", "libdcap_qvl_darwin_amd64.a", false},
		{"darwin", "arm64", "libdcap_qvl_darwin_arm64.a", false},
		{"windows", "amd64", "", true},
		{"linux", "386", "", true},
	}

	for _, tt := range tests {
		got, err := platformAssetName(tt.goos, tt.goarch)
		if tt.wantErr && err == nil {
			t.Fatalf("%s/%s: expected error", tt.goos, tt.goarch)
		}
		if !tt.wantErr && err != nil {
			t.Fatalf("%s/%s: unexpected error: %v", tt.goos, tt.goarch, err)
		}
		if got != tt.want {
			t.Fatalf("%s/%s: got %q want %q", tt.goos, tt.goarch, got, tt.want)
		}
	}
}

func TestParseChecksums(t *testing.T) {
	input := `
# generated by sha256sum
1111111111111111111111111111111111111111111111111111111111111111  libdcap_qvl_linux_amd64.a
2222222222222222222222222222222222222222222222222222222222222222 *libdcap_qvl_darwin_arm64.a
`
	got, err := parseChecksums(input)
	if err != nil {
		t.Fatalf("parseChecksums error: %v", err)
	}
	if got["libdcap_qvl_linux_amd64.a"] != strings.Repeat("1", 64) {
		t.Fatalf("missing/invalid linux checksum")
	}
	if got["libdcap_qvl_darwin_arm64.a"] != strings.Repeat("2", 64) {
		t.Fatalf("missing/invalid darwin checksum")
	}
}

func TestParseChecksumsRejectsBadLine(t *testing.T) {
	_, err := parseChecksums("abcdef")
	if err == nil {
		t.Fatal("expected parse error")
	}
}

func TestReleaseURLs(t *testing.T) {
	got := releaseAssetURL("https://github.com", "org/repo", "v1.2.3", "x.a")
	if got != "https://github.com/org/repo/releases/download/v1.2.3/x.a" {
		t.Fatalf("unexpected release url: %s", got)
	}

	got = releaseLatestAPIURL("https://api.github.com", "org/repo")
	if got != "https://api.github.com/repos/org/repo/releases/latest" {
		t.Fatalf("unexpected latest api url: %s", got)
	}
}

func TestFetchLatestReleaseTag(t *testing.T) {
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.URL.Path != "/repos/org/repo/releases/latest" {
			http.NotFound(w, r)
			return
		}
		w.WriteHeader(http.StatusOK)
		_, _ = w.Write([]byte(`{"tag_name":"v9.9.9"}`))
	}))
	defer srv.Close()

	tag, err := fetchLatestReleaseTag(context.Background(), srv.Client(), srv.URL, "org/repo")
	if err != nil {
		t.Fatalf("fetchLatestReleaseTag error: %v", err)
	}
	if tag != "v9.9.9" {
		t.Fatalf("got tag %q", tag)
	}
}

func TestFetchLatestReleaseTagHTTPErrorType(t *testing.T) {
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		http.NotFound(w, r)
	}))
	defer srv.Close()

	_, err := fetchLatestReleaseTag(context.Background(), srv.Client(), srv.URL, "org/repo")
	if err == nil {
		t.Fatal("expected error")
	}
	var httpErr *httpStatusError
	if !errors.As(err, &httpErr) {
		t.Fatalf("expected httpStatusError, got %T", err)
	}
	if httpErr.StatusCode != http.StatusNotFound {
		t.Fatalf("unexpected status code: %d", httpErr.StatusCode)
	}
}

func TestFileMatchesSHA256(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "x.a")
	if err := os.WriteFile(path, []byte("abc"), 0o644); err != nil {
		t.Fatalf("write file: %v", err)
	}
	const shaABC = "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad"

	ok, err := fileMatchesSHA256(path, shaABC)
	if err != nil {
		t.Fatalf("fileMatchesSHA256 error: %v", err)
	}
	if !ok {
		t.Fatal("expected checksum match")
	}
}

func TestShellSingleQuote(t *testing.T) {
	got := shellSingleQuote("a'b")
	if got != `'a'"'"'b'` {
		t.Fatalf("unexpected quoted string: %s", got)
	}
}

func TestIsHTTPStatus(t *testing.T) {
	err := &httpStatusError{StatusCode: http.StatusNotFound}
	if !isHTTPStatus(err, http.StatusNotFound) {
		t.Fatal("expected status match")
	}
	if isHTTPStatus(err, http.StatusForbidden) {
		t.Fatal("expected status mismatch")
	}
	if isHTTPStatus(errors.New("boom"), http.StatusNotFound) {
		t.Fatal("expected non-http error mismatch")
	}
}
